### ISSUE TITLE
[BE] : 로그아웃 처리

### ISSUE THREAD

**Issue by Eunjinshin** [codestates-seb/seb42_main_025#39]
### 만들고자 하는 기능이 무엇인가요?
로그아웃 기능 구현

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 로그인한 회원의 로그아웃 구현

### 예상 작업 시간
6h

**Comment by Eunjinshin** [comment]
"path" 가 /login으로 이동해버리는 이슈가 발생
오늘(15일)부터 수정중

**Comment by JiSun11** [comment]
로그아웃 실행 시 /login으로 이동하는 오류 수정함
